### ISSUE TITLE
unable to make the toggle do anything

### ISSUE THREAD

**Issue by civiks** [alfredapp/low-power-mode-workflow#2] opened 2022-08-01 18:14 UTC
### Workflow version

2022.4

### Alfred version

5.0[2064]

### macOS version

Ventura 13.0

### Debugger output

```alfred_debugger
[23:40:29.438] Low Power Mode[Script Filter] Queuing argument '(null)'
[23:40:29.513] Low Power Mode[Script Filter] Script with argv '(null)' finished
[23:40:29.518] Low Power Mode[Script Filter] {"items":[{"title":"Battery’s Low Power Mode is On","subtitle":"Action to turn it off","arg":["battery","off"],"icon":{"path":"images/icon_battery_on.png"}},{"title":"AC’s Low Power Mode is On","subtitle":"Action to turn it off","arg":["adapter","off"],"icon":{"path":"images/icon_adapter_on.png"}}]}
[23:40:36.444] Low Power Mode[Script Filter] Processing complete
[23:40:36.445] Low Power Mode[Script Filter] Passing output '(
    battery,
    off
)' to Run Script
[23:40:44.850] ERROR: Low Power Mode[Run Script] /Users/souvik/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/EBFA9754-E1A3-4738-9FA7-08744C34480D: execution error: Error: Error: Can't get object. (-1728)
[23:40:44.860] Low Power Mode[Run Script] Processing complete
[23:40:44.862] Low Power Mode[Run Script] Passing output '' to Run Script
```

### More details

So, i just typed `lpm` and hit enter and it was unable to toggle the state. 
The error log was pretty much the same as here [https://github.com/alfredapp/low-power-mode-workflow/issues/1#issue-1209388638](url) , and i did check and yes, my system language is set to English(US).

**Comment by vitorgalvao** [comment] 2022-08-01 19:02
The issue is that you’re on Ventura and the System Preferences app has changed. Because we need to rely on GUI scripting, it needs to adapt to the new app.

I only have access to one Mac which supports Ventura, so moving that to a beta OS this soon is a no-go. On a VM, the battery pane doesn’t show in the Settings app so I can’t test this yet. I’ll review a pull request or work with indications on how the new panel is laid out, but otherwise don’t have access to it myself. macOS betas are not officially supported.

A screenshot of the battery pane on Ventura, if you want to provide it, might help.

**Comment by civiks** [comment] 2022-08-01 19:45
yup, the panel layout has definitely changed and i tried changing out some values in the script and narrowed it down to the checkbox thingy, its a dropdown
![image](https://user-images.githubusercontent.com/59787884/182232299-1de447e7-071d-44ff-8e79-155a984bbde2.png)

**Comment by vitorgalvao** [comment] 2022-08-11 18:37
The screenshot does help to understand the direction. Started looking into it by changing other panels, but that’s quite cumbersome and I’d still need to ask for someone else to test it, which would require some back and forth.

Closing for now, I’ll revisit when Ventura is out of beta.

**Closed as completed by vitorgalvao** 2022-08-11 18:37 UTC

**Comment by vitorgalvao** [comment] 2022-10-27 02:05
Support for Ventura System Settings has been added in 2022.7.
