### ISSUE TITLE
[Ventura 13.2] Macbook Pro M2 Pro/Max

### ISSUE THREAD

**Issue by Ramalama2** [alfredapp/low-power-mode-workflow#4] opened 2023-01-27 23:42 UTC
### Workflow version

2022.8

### Alfred version

5.0.6

### macOS version

13.2

### Debugger output

```alfred_debugger
[00:20:18.236] Logging Started...
[00:20:32.379] Low Power Mode[Script Filter] Queuing argument '(null)'
[00:20:32.439] Low Power Mode[Script Filter] Script with argv '(null)' finished
[00:20:32.444] ERROR: Low Power Mode[Script Filter] Code 1: /Users/rama/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/0547CEE0-7E26-4A3C-8A29-3C7F54DE3ED4: execution error: Error: TypeError: null is not an object (evaluating 'batteryMatch[1]') (-2700)
```

### More details

<img width="819" alt="SCR-20230128-li" src="https://user-images.githubusercontent.com/6314556/215224517-141c5375-643e-4d4d-b306-1873767311b5.png">

Hey Buddy, with the new M2 MacBooks, the setting was moved from a top "tickable box" to a "dropdown setting" on AC or Battery.

I dont actually know what Apple has smoked, but they seems like they like to move things around xD
Actually the only thing that matters is just "Battery", cause no one need energy saving on AC mode.

I readed in another issue that you don't have access to ventura and probably not to any new of those macbooks, so if you need sth, ask me.
I can provide Remotedesktop or whatever you need.

The only thing i find strange is, that youre using sth like an emulated mousepointer way.
cant you do it via command? like "sudo pmset -a lowpowermode 1" ?

Sure that requires sudo authentification, but we can simply allow it via visudo:
nano /private/etc/sudoers.d/lpm
and add:
rama ALL = NOPASSWD: /usr/bin/pmset -a lowpowermode 1, /usr/bin/pmset -a lowpowermode 0

then you get the ability to enable explicitly LPM without a password.
sudo /usr/bin/pmset -a lowpowermode 1

Cheers!

**Comment by vitorgalvao** [comment] 2023-01-28 00:44
I’m on Ventura already, and the workflow works on it. Though it does seem it now needs an extra half a second to register. [2023.1](https://github.com/alfredapp/low-power-mode-workflow/releases/tag/2023.1) fixes it and now opens System Settings in the foreground. It will be in the Gallery soon.

> Sure that requires sudo authentification

That’s the reason it isn’t done that way. If it didn’t require `sudo`, that’s how I’d do it.

> but we can simply allow it via visudo

Most users won’t know how to do that, though, it’s an advanced approach which can lead to very bad results if done wrong. This is an official workflow which reaches a lot of users of different skill levels which have to be taken into consideration.

The alternative would be to request authentication every time. While that might not be be too inconvenient for people with Touch ID Macs, for everyone else it means typing the password every time.

Thank you for the report!

**Closed as completed by vitorgalvao** 2023-01-28 00:44 UTC

**Comment by Ramalama2** [comment] 2023-01-28 00:50
Thanks, im gonna try out the new version!

Otherwise i did the sudo approach in the meantime, which should work on any macos updates.
It just requires this: /private/etc/sudoers.d/lpm
`rama ALL = NOPASSWD: /usr/bin/pmset -a lowpowermode 1, /usr/bin/pmset -a lowpowermode 0`
[Enery Saving.zip](https://github.com/alfredapp/low-power-mode-workflow/files/10524184/Enery.Saving.zip)

Cheers!

**Comment by Ramalama2** [comment] 2023-01-28 00:54
> 
v2023.1 still doesn't works sadly...
```
[01:52:41.481] Low Power Mode[Script Filter] Queuing argument '(null)'
[01:52:41.545] Low Power Mode[Script Filter] Script with argv '(null)' finished
[01:52:41.550] ERROR: Low Power Mode[Script Filter] Code 1: /Users/rama/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/7659DC16-C8CF-433E-B995-47D3D9C06E6A: execution error: Error: TypeError: null is not an object (evaluating 'batteryMatch[1]') (-2700)
```

**Comment by vitorgalvao** [comment] 2023-01-28 01:49
That’s an error in another part. What do you get with `/usr/bin/pmset -g custom`?

**Comment by Ramalama2** [comment] 2023-01-28 02:09
```
rama@MBPvonAlexander ~ % /usr/bin/pmset -g custom
Battery Power:
 Sleep On Power Button 1
 powermode            1
 standby              1
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 hibernatefile        /var/vm/sleepimage
 displaysleep         2
 womp                 0
 networkoversleep     0
 sleep                1
 lessbright           1
 tcpkeepalive         1
 disksleep            10
AC Power:
 Sleep On Power Button 1
 powermode            1
 standby              1
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 hibernatefile        /var/vm/sleepimage
 displaysleep         10
 womp                 1
 networkoversleep     0
 sleep                1
 tcpkeepalive         1
 disksleep            10
```

Sorry, i doodled away, 3am here xD
everything that changes ist the powermode (1=LPM) & (0=Auto)

**Comment by vitorgalvao** [comment] 2023-01-28 02:22
How bizarre. Compare it to this one:

```
Battery Power:
 Sleep On Power Button 1
 lowpowermode         1
 standby              1
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 hibernatefile        /var/vm/sleepimage
 displaysleep         2
 womp                 0
 networkoversleep     0
 sleep                1
 lessbright           0
 tcpkeepalive         1
 disksleep            10
AC Power:
 Sleep On Power Button 1
 lowpowermode         0
 standby              1
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 hibernatefile        /var/vm/sleepimage
 displaysleep         10
 womp                 1
 networkoversleep     0
 sleep                1
 tcpkeepalive         1
 disksleep            10
```

Note how yours is missing `lowpowermode` but has a `powermode` instead. Can you confirm if changing Lower Power Mode in System Settings also changes that value? And which value (`0` or `1`) corresponds to which value (Low Power Mode off or on).

**Comment by Ramalama2** [comment] 2023-01-28 02:52
Thats exactly the case, you can set "lowpowermode" but the right way to get it again is with "powermode" xD
I dont know why apple does this, but yes: 0 is automatic, 1 is enabled, 2 is high performance

lowpowermode is just an synonym for powermode, means:
```
sudo /usr/bin/pmset -a lowpowermode 0
sudo /usr/bin/pmset -a lowpowermode 1
sudo /usr/bin/pmset -a lowpowermode 2
sudo /usr/bin/pmset -a powermode 0 
sudo /usr/bin/pmset -a powermode 1
sudo /usr/bin/pmset -a powermode 2
```
This makes no difference if you use "lowpowermode" or "powermode".
Just when you want to grab it, you need to use "powermode", because "pmset -g lowpowermode" doesn't exist.
while you can use "pmset -a lowpowermode [0|1|2]"...
i think the devs at apple were drunk xD

Thats why im using in my custom workflow that i posted above in the zip file, this bash script:
```
if [[ $(/usr/bin/pmset -g | grep powermode | awk '{print $NF}') == "0" ]]; then
    sudo /usr/bin/pmset -a lowpowermode 1
    echo -n "Low Power Mode - ENABLED!"
else
    sudo /usr/bin/pmset -a lowpowermode 0
    echo -n "Low Power Mode - DISABLED!"
fi
```
don't ask me why im using there "lowpowermode", maybe because it sounds better xD

**Comment by vitorgalvao** [comment] 2023-01-28 02:56
> 2 is high performance

Can I see the System Setting window, in English, with the dropdown open? Seems like you may have more options than I do.

**Comment by Ramalama2** [comment] 2023-01-28 03:18
<img width="734" alt="Screenshot 2023-01-28 at 04 16 29" src="https://user-images.githubusercontent.com/6314556/215239461-325fc305-2319-4122-b285-add70aafe306.png">

**Comment by vitorgalvao** [comment] 2023-01-28 21:01
Seems like that’s a Pro/Max thing. I get:

![](https://raw.githubusercontent.com/alfredapp/low-power-mode-workflow/main/Workflow/images/about/settings.png)

That kind of throws a wrench on the whole thing, I’ll have a think about this. You do have an “Automatic” option, so this doesn’t seem as necessary on those processors. I’ll see if I get more feedback from people on those processors too.

**Comment by Ramalama2** [comment] 2023-01-28 21:26
Yeah, im pretty sure thats new with the M2 Max/Pro Macbooks.

I see no reason that "Automatic" mode doesnt come to M1 Macbooks, because its the same chip, just with 2 ecores less and normal clocked. (My M2 is pretty sure just an Overclocked M1 + little bit more cache)

Or probably apple wont bring it to m1, cause 2ecores is in "Apples Opinion" not enough to be usable without performance cores, we will see...

However, for myself i have my script that works pretty nice already, so i am happy already xD

Thanks anyway vitor, that you looked into this.
Cheers

**Comment by vitorgalvao** [comment] 2023-11-15 12:11
@Ramalama2 I’ve rethought this a bit. [This version](https://github.com/alfredapp/low-power-mode-workflow/files/13364267/Low.Power.Mode.alfredworkflow.zip) uses `pmset` and requires authentication (shown via a GUI) instead of opening System Settings. It seems authentication is now sometimes required even to change the option in the GUI so there’s little reason to not use the alternative.

The workflow above should also work for your chip to toggle between Lower Power Mode and Automatic, and it should do it on a per power-source basis (i.e. it can toggle either the battery or the adapter).

I understand you’re happy with your own solution, but if you’re interested in testing out the above, it would be useful to have data from other chips. Do note that while the workflow should immediately pick up changes, System Settings doesn’t if it’s open at the time (i.e. it would need to be closed and reopened for the change to be visible).

**Comment by Ramalama2** [comment] 2024-01-05 17:05
@vitorgalvao Sorry for the very late Reply, im not tracking github notifications very often :-(

However, your solution works very well, just tested!
But its absolutely unhandy, because i have to type everytime my password, there is no option for fingerprint at least.
With everytime i mean on every toggle, even if the last one is 1 second ago.
With my solution i don't need any passwords/authentication/fingerprint at all.

The icons and everything is cool, but yeah.
But you know that already anyway, however you asked me to test, i did and it works perfectly exactly as you wrote.

I think to be honest, as im the only one that requested this, probably no one else needs it? i don't know.

Cheers :-)

**Comment by vitorgalvao** [comment] 2024-01-05 19:25
Thank you for testing.

> i have to type everytime my password, there is no option for fingerprint at least.

Strange. I can reproduce that but I thought that wasn’t necessary before. Maybe it’s a change in Sonoma, or I’m misremembering something. Will see if I can figure it out.

Either way gave me the idea to make both methods available, which should be out in a later version.
